version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=express-ts
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME_LOCAL=express-ts
      - DB_USER_LOCAL=postgres
      - DB_PASSWORD_LOCAL=postgres
      - DB_HOST_LOCAL=db